/**
 * /share/[token] — Public ISR snapshot page
 * Strategy: ISR with on-demand revalidation
 * Justification (ADR-001): Public SEO page. Statically generated at build/first-request,
 * served from CDN edge. On-demand revalidation via revalidateTag('share') when
 * the dashboard is updated. No JS required for the read-only render → Lighthouse ≥95.
 */
import { notFound } from 'next/navigation'

const API = process.env.NEXT_PUBLIC_API_BASE || 'http://localhost:4000'

// ISR — revalidate on-demand only (webhook from mock when dashboard changes)
export const revalidate = false

export async function generateMetadata({ params }) {
  try {
    const res = await fetch(`${API}/api/share/${params.token}`, { next: { tags: ['share'] } })
    if (!res.ok) return { title: 'Dashboard — ObsConsole' }
    const data = await res.json()
    return {
      title: `${data.dashboard?.name || 'Dashboard'} — ObsConsole`,
      description: 'Shared observability dashboard',
      robots: { index: true, follow: false },
    }
  } catch { return { title: 'Dashboard — ObsConsole' } }
}

export default async function SharePage({ params }) {
  let data
  try {
    const res = await fetch(`${API}/api/share/${params.token}`, { next: { tags: ['share'] } })
    if (!res.ok) notFound()
    data = await res.json()
  } catch { notFound() }

  const { dashboard } = data
  const widgets = dashboard?.widgets || []

  return (
    <div style={{ minHeight:'100vh', background:'#030712', color:'#cbd5e1',
      fontFamily:'JetBrains Mono, monospace', padding:0 }}>

      {/* SEO-friendly header — renders without JS */}
      <header style={{ padding:'16px 24px', borderBottom:'1px solid #0f1a2e',
        background:'#080d16', display:'flex', alignItems:'center', gap:12 }}>
        <div style={{ width:22,height:22,borderRadius:5,
          background:'linear-gradient(135deg,#0ea5e9,#6366f1)',
          display:'flex',alignItems:'center',justifyContent:'center',
          fontWeight:900,color:'#fff',fontSize:12 }}>O</div>
        <span style={{ fontWeight:700, color:'#f1f5f9', fontSize:14 }}>ObsConsole</span>
        <span style={{ fontSize:10, color:'#334155', marginInlineStart:'auto' }}>
          Public dashboard snapshot
        </span>
      </header>

      <main style={{ padding:24 }}>
        <h1 style={{ fontSize:20, fontWeight:600, color:'#f1f5f9', marginBottom:4 }}>
          {dashboard?.name || 'Dashboard'}
        </h1>
        <p style={{ fontSize:11, color:'#475569', marginBottom:24 }}>
          Read-only snapshot · Token: {params.token}
        </p>

        {widgets.length === 0 ? (
          <p style={{ color:'#334155' }}>This dashboard has no widgets.</p>
        ) : (
          <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fill,minmax(260px,1fr))', gap:12 }}>
            {widgets.map(w => (
              <article key={w.id} style={{ background:'#080d16', border:'1px solid #0f172a',
                borderRadius:8, padding:20 }}>
                <div style={{ fontSize:9,color:'#475569',fontWeight:700,
                  textTransform:'uppercase',letterSpacing:'.08em',marginBottom:8 }}>
                  {w.type}
                </div>
                <h2 style={{ fontSize:14, fontWeight:700, color:'#f1f5f9', marginBottom:6 }}>
                  {w.title}
                </h2>
                <div style={{ fontSize:11, color:'#334155' }}>
                  Service: {w.serviceId}
                </div>
                <div style={{ height:48, background:'#040810', borderRadius:4, marginTop:10,
                  display:'flex', alignItems:'center', justifyContent:'center',
                  fontSize:11, color:'#1e293b' }}>
                  static snapshot
                </div>
              </article>
            ))}
          </div>
        )}
      </main>

      <footer style={{ padding:'16px 24px', borderTop:'1px solid #0f1a2e', marginTop:40,
        fontSize:10, color:'#1e293b' }}>
        Generated by ObsConsole · Read-only public link
      </footer>
    </div>
  )
}
